import type { Metadata } from 'next'
import './globals.css'
import Modal from '@/components/Modal'


export const metadata: Metadata = {
  title: 'Trello-App',
  description: 'Generated by the PApAFAM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#fff]'>
        {children}
        <Modal/>
        </body>
    </html>
  )
}
